include(":app",
        ":featureTester",
        ":common:base.cache",
        ":common:base.network",
        ":common:base.presentation",
        ":common:base.navigation",
        ":common:base.view",
        ":common:base.debug_tools",
        ":common:base.test_tools",
        ":shared:lib.spotify_api",
        ":features:feat.home"
)
