include(":app",
        ":common:base.cache",
        ":common:base.network",
        ":common:base.presentation",
        ":common:base.navigation",
        ":common:base.view",
        ":common:base.debug_tools",
        ":shared:lib.spotify_api",
        ":features:feat.login",
        ":features:feat.home",
        ":features:feat.search"
)
