name: detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.11.0
        with:
          args: --fail-fast --config Detekt.yml
