name: Unit Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create gradle.properties
        env:
          SPOTIFY_CLIENT: ${{ secrets.SPOTIFYCLIENT }}
          SPOTIFY_SECRET: ${{ secrets.SPOTIFYSECRET }}
        run: echo "" >> ./gradle.properties;
          echo spotifyClient=\"SPOTIFY_CLIENT\" >> ./gradle.properties;
          echo spotifySecret=\"SPOTIFY_SECRET\" >> ./gradle.properties;

      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: reports
          path: app/build/test-results # path to where the xml test results are stored

  report:
    runs-on: ubuntu-latest
    needs: test # The report job will run after test job
    if: ${{ always() }} # IMPORTANT: Execute report job regardless of status
    steps:
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
